'use client'

import { useEffect, useMemo, useState } from 'react'
import { Banknote, Building2, ReceiptText, Smartphone, WalletCards } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import type { AdminCustomer, PaymentMethod, PaymentType, RecentCollection } from '@/lib/types/admin'
import { matchesCustomerSearch, money, monthLabel } from '@/lib/utils/paymentAccounting'

type Bill = { id: string; user_id: string; connection_id: string; amount: number; amount_paid: number; unpaid_amount: number; billing_month: string; payment_status: 'paid' | 'partial' | 'unpaid'; customer_id_snapshot: string | null; customer_name_snapshot: string | null; zone_snapshot: string | null; package_name_snapshot: string | null; payment_dates: string[]; collector_names: string[] }
type Partial = Bill & { customer?: AdminCustomer; connection?: AdminCustomer['connection'] }
type Advance = RecentCollection & { customer?: AdminCustomer; connection?: AdminCustomer['connection']; months_covered: number; paid_through: string | null; next_billing: Bill | null }
const methods: Array<[PaymentMethod, typeof Banknote, string]> = [['cash', Banknote, 'Cash'], ['bkash', Smartphone, 'bKash'], ['nagad', WalletCards, 'Nagad'], ['bank', Building2, 'Bank']]
const paymentTypes: Array<[PaymentType, string]> = [['full', 'Full Payment'], ['partial', 'Partial Payment'], ['advance', 'Advance Payment']]

export default function CollectionsPage() {
  const [customers, setCustomers] = useState<AdminCustomer[]>([]); const [records, setRecords] = useState<RecentCollection[]>([]); const [history, setHistory] = useState<Bill[]>([])
  const [partials, setPartials] = useState<Partial[]>([]); const [advances, setAdvances] = useState<Advance[]>([]); const [availableMonths, setAvailableMonths] = useState<string[]>([])
  const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7)); const [totals, setTotals] = useState({ expected: 0, collected: 0, unpaid: 0, partialOutstanding: 0, advanceCollected: 0, todayCollection: 0 })
  const [zone, setZone] = useState(''); const [customerId, setCustomerId] = useState(''); const [paymentType, setPaymentType] = useState<PaymentType>('full'); const [amount, setAmount] = useState(''); const [method, setMethod] = useState<PaymentMethod>('cash'); const [note, setNote] = useState(''); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true)
  const load = async (month = selectedMonth) => { setLoading(true); try { const response = await fetch(`/api/admin/collections?month=${month}`, { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Unable to load collections.'); setCustomers(data.customers); setRecords(data.records); setHistory(data.history); setPartials(data.partialBalances); setAdvances(data.advancePayments); setAvailableMonths(data.availableMonths); setTotals(data.totals); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load collections.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const selected = customers.find(customer => customer.id === customerId); const currentBill = selected?.unpaid_billing as (Bill | null | undefined); const due = currentBill?.unpaid_amount ?? currentBill?.amount ?? selected?.connection?.monthly_price ?? 0; const alreadyPaid = Math.max((currentBill?.amount ?? selected?.connection?.monthly_price ?? 0) - due, 0)
  const zones = useMemo(() => Array.from(new Set(customers.map(customer => customer.zone ?? 'Unassigned'))).sort(), [customers]); const visibleCustomers = customers.filter(customer => customer.zone === zone)
  const selectCustomer = (id: string, preferredType: PaymentType = paymentType) => { const customer = customers.find(item => item.id === id); const bill = customer?.unpaid_billing as (Bill | null | undefined); const remaining = bill?.unpaid_amount ?? bill?.amount ?? customer?.connection?.monthly_price ?? 0; setCustomerId(id); setPaymentType(preferredType); setAmount(preferredType === 'full' ? String(remaining) : ''); }
  const changeType = (type: PaymentType) => { setPaymentType(type); setAmount(type === 'full' ? String(due) : '') }
  const save = async () => { if (!selected || !amount) return; setSaving(true); try { const response = await fetch('/api/admin/collections', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: selected.id, amount: Number(amount), paymentType, paymentMethod: method, referenceNote: note }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Unable to save payment.'); setCustomerId(''); setAmount(''); setNote(''); setPaymentType('full'); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to save payment.') } finally { setSaving(false) } }
  const numericAmount = Number(amount) || 0; const advanceMonths = selected?.connection?.monthly_price ? Math.floor(numericAmount / selected.connection.monthly_price) : 0
  const collectDue = (item: Partial) => { const customer = customers.find(customer => customer.id === item.user_id); if (!customer) return; setZone(customer.zone ?? ''); selectCustomer(customer.id, 'full'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const card = (label: string, value: number) => <article key={label} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold">{money(value)}</p></article>

  return <main className="pb-10 pt-4 sm:pb-12 sm:pt-6"><div className="mx-auto w-full max-w-6xl space-y-5 px-4 sm:space-y-6 sm:px-6">
    <section className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Payment Collection</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Collections</h1><p className="mt-1 text-sm text-muted-foreground">Zone → Customer → payment details → method → save.</p></div><select aria-label="Billing month" value={selectedMonth} onChange={event => { setSelectedMonth(event.target.value); void load(event.target.value) }} className="h-10 rounded-md border border-input bg-background px-3 text-sm">{Array.from(new Set([`${new Date().toISOString().slice(0, 7)}-01`, ...availableMonths])).sort().reverse().map(month => <option key={month} value={month.slice(0, 7)}>{monthLabel(month)}</option>)}</select></section>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-3">{card('Monthly Expected', totals.expected)}{card('Monthly Collected', totals.collected)}{card('Monthly Unpaid', totals.unpaid)}{card('Partial Outstanding', totals.partialOutstanding)}{card('Advance Collected', totals.advanceCollected)}{card("Today's Collection", totals.todayCollection)}</section>
    {error && <p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}
    {loading ? <section className="rounded-3xl border border-border bg-card p-12 text-center text-muted-foreground">Loading collections…</section> : <section className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
      <div className="rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-5"><div className="mb-5 flex gap-3"><div className="rounded-2xl bg-primary/10 p-3"><ReceiptText className="h-5 w-5 text-primary" /></div><div><h2 className="font-bold">Collect Payment</h2><p className="text-xs text-muted-foreground">Select a zone first, then its customer.</p></div></div><div className="space-y-4">
        <label className="block text-sm font-medium">Zone<select value={zone} onChange={event => { setZone(event.target.value); setCustomerId(''); setAmount('') }} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3"><option value="">Select zone</option>{zones.map(item => <option key={item}>{item}</option>)}</select></label>
        <label className="block text-sm font-medium">Customer<select disabled={!zone} value={customerId} onChange={event => selectCustomer(event.target.value)} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3"><option value="">Select customer</option>{visibleCustomers.map(customer => <option key={customer.id} value={customer.id}>{customer.name} · {customer.phone ?? 'No phone'}</option>)}</select></label>
        {selected && <div className="rounded-2xl bg-muted/50 p-3 text-sm"><p>Name: <b>{selected.name}</b></p><p className="mt-1">Customer ID: <b>{selected.customer_id}</b></p><p className="mt-1">Username: <b>{selected.username ?? '—'}</b></p><p className="mt-1">Package: <b>{selected.connection?.package_name ?? '—'}</b></p><p className="mt-1">Monthly bill: <b>{money(selected.connection?.monthly_price ?? 0)}</b></p><p className="mt-1">Current billing month: <b>{monthLabel(currentBill?.billing_month)}</b></p><p className="mt-1">Already paid: <b>{money(alreadyPaid)}</b></p><p className="mt-1">Remaining due: <b>{money(due)}</b></p><p className="mt-1">Status: <b className="capitalize">{currentBill?.payment_status ?? 'unpaid'}</b></p></div>}
        <label className="block text-sm font-medium">Payment Type<select value={paymentType} onChange={event => changeType(event.target.value as PaymentType)} className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3">{paymentTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
        <label className="block text-sm font-medium">Amount<Input type="number" min="0" value={amount} readOnly={paymentType === 'full'} onChange={event => setAmount(event.target.value)} className="mt-2 h-11" /></label>
        {selected && paymentType === 'partial' && <div className="rounded-xl bg-primary/5 p-3 text-sm"><p>Monthly Bill: <b>{money(selected.connection?.monthly_price ?? 0)}</b></p><p>Already Paid: <b>{money(alreadyPaid)}</b></p><p>Paying Now: <b>{money(numericAmount)}</b></p><p>Remaining After Payment: <b>{money(Math.max(due - numericAmount, 0))}</b></p></div>}
        {selected && paymentType === 'advance' && <div className="rounded-xl bg-primary/5 p-3 text-sm"><p>Payment: <b>{money(numericAmount)}</b></p><p>Monthly Package: <b>{money(selected.connection?.monthly_price ?? 0)}</b></p><p>Coverage: <b>{advanceMonths} full month{advanceMonths === 1 ? '' : 's'}{numericAmount % (selected.connection?.monthly_price || 1) ? ' + partial' : ''}</b></p><p>Paid Through: <b>{advanceMonths ? monthLabel(new Date(new Date().getFullYear(), new Date().getMonth() + advanceMonths - 1, 1).toISOString()) : 'No fully covered month yet'}</b></p></div>}
        <div><p className="mb-2 text-sm font-medium">Payment Method</p><div className="grid grid-cols-2 gap-2">{methods.map(([key, Icon, label]) => <button key={key} type="button" onClick={() => setMethod(key)} className={`flex h-11 items-center justify-center gap-2 rounded-xl border text-sm font-medium ${method === key ? 'border-primary bg-primary text-primary-foreground' : 'border-border'}`}><Icon className="h-4 w-4" />{label}</button>)}</div></div><label className="block text-sm font-medium">Reference / Note<Input value={note} onChange={event => setNote(event.target.value)} className="mt-2 h-11" placeholder="Optional" /></label><Button size="lg" onClick={save} disabled={!selected || !amount || saving} className="h-11 w-full">{saving ? 'Saving…' : 'Collect'}</Button>
      </div></div>
      <div className="rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-5"><h2 className="font-bold">Recent Collections</h2><p className="mb-4 text-xs text-muted-foreground">Cash receipts retain their actual collection time.</p><div className="space-y-3">{records.slice(0, 15).map(record => <article key={record.id} className="flex justify-between gap-3 rounded-2xl border border-border p-4"><div><p className="font-semibold">{record.customer_name}</p><p className="text-xs text-muted-foreground">{record.payment_type} · {record.payment_method} · {new Date(record.created_at).toLocaleString()}</p><p className="mt-1 text-xs text-muted-foreground">Collected by {record.collector_name}</p></div><p className="font-bold text-primary">{money(record.amount)}</p></article>)}{!records.length && <p className="py-12 text-center text-sm text-muted-foreground">No collections yet.</p>}</div></div>
    </section>}
    {!loading && <Queues partials={partials} advances={advances} search={search} setSearch={setSearch} collectDue={collectDue} />}
    {!loading && <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border p-4"><h2 className="font-bold">Monthly Bill History</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{['Customer','Package','Bill','Paid','Remaining','Collected by','Status'].map(label => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{history.map(bill => <tr key={bill.id} className="border-t border-border"><td className="px-4 py-3"><b>{bill.customer_name_snapshot}</b><p className="text-xs text-muted-foreground">{bill.customer_id_snapshot} · {bill.zone_snapshot}</p></td><td className="px-4 py-3">{bill.package_name_snapshot}</td><td className="px-4 py-3">{money(bill.amount)}</td><td className="px-4 py-3">{money(bill.amount_paid)}</td><td className="px-4 py-3">{money(bill.unpaid_amount)}</td><td className="px-4 py-3">{bill.collector_names.length ? bill.collector_names.join(', ') : '—'}</td><td className="px-4 py-3 capitalize">{bill.payment_status}</td></tr>)}</tbody></table></div></section>}
  </div></main>
}

function Queues({ partials, advances, search, setSearch, collectDue }: { partials: Partial[]; advances: Advance[]; search: string; setSearch: (value: string) => void; collectDue: (item: Partial) => void }) {
  const matches = (item: { customer?: AdminCustomer; customer_id_snapshot?: string | null; customer_name_snapshot?: string | null }) => matchesCustomerSearch(search, item.customer ?? { customer_id: item.customer_id_snapshot, name: item.customer_name_snapshot })
  return <section className="space-y-5"><div className="rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Partial Payments</h2><p className="text-xs text-muted-foreground">Customers with a remaining balance.</p></div><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search name, username or customer ID" className="max-w-sm" /></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr>{['Customer','Zone','Package','Monthly Bill','Already Paid','Remaining Due','Billing Month',''].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{partials.filter(matches).map(item => <tr key={item.id} className="border-t border-border"><td className="p-2"><b>{item.customer?.name ?? item.customer_name_snapshot}</b><p className="text-xs text-muted-foreground">{item.customer?.customer_id ?? item.customer_id_snapshot} · {item.customer?.username ?? '—'}</p></td><td className="p-2">{item.customer?.zone ?? item.zone_snapshot}</td><td className="p-2">{item.connection?.package_name ?? item.package_name_snapshot}</td><td className="p-2">{money(item.amount)}</td><td className="p-2">{money(item.amount_paid)}</td><td className="p-2">{money(item.unpaid_amount)}</td><td className="p-2">{monthLabel(item.billing_month)}</td><td className="p-2"><Button size="sm" onClick={() => collectDue(item)}>Collect Due</Button></td></tr>)}{!partials.filter(matches).length && <tr><td colSpan={8} className="p-5 text-center text-muted-foreground">No partial balances.</td></tr>}</tbody></table></div></div>
    <div className="rounded-3xl border border-border bg-card p-4 shadow-sm sm:p-5"><h2 className="font-bold">Advance Payments</h2><p className="text-xs text-muted-foreground">Future coverage is shown only through fully paid months.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr>{['Customer','Package','Monthly Price','Advance Received','Covered','Paid Through','Next billing/status'].map(label => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{advances.filter(matches).map(item => <tr key={item.id} className="border-t border-border"><td className="p-2"><b>{item.customer?.name}</b><p className="text-xs text-muted-foreground">{item.customer?.customer_id} · {item.customer?.username ?? '—'}</p></td><td className="p-2">{item.connection?.package_name}</td><td className="p-2">{money(item.connection?.monthly_price ?? 0)}</td><td className="p-2">{money(item.amount)}</td><td className="p-2">{item.months_covered} month(s)</td><td className="p-2">{monthLabel(item.paid_through)}</td><td className="p-2">{item.next_billing ? `${monthLabel(item.next_billing.billing_month)} · ${item.next_billing.payment_status}` : '—'}</td></tr>)}{!advances.filter(matches).length && <tr><td colSpan={7} className="p-5 text-center text-muted-foreground">No advance payments.</td></tr>}</tbody></table></div></div></section>
}
